### ISSUE TITLE
Is it possible to have the loading effect semi-opague?

### ISSUE THREAD

**Issue by rayluo** [rayluo/brython-project-template#4]
Hi @iansparks , do you know whether it is possible to have the loading effect semi-opaque, so that the real page content is visible for the end user to read? This way is the loading time won't be wasted in waiting, but allow the end user to read some instruction etc..

Besides, currently the real page would still be shown on the screen for a very short time (roughly less than a second), before the full-screen loading effect kicks in. And later it would be shown again. I suppose a semi-opaque loading effect would make all those transition more natural.

**Comment by iansparks** [comment]
Sure @rayluo. If you change the loader css building in loader.js like this:

```
'div#brython_template_loading_animation {',
'  overflow: hidden;',
'  position: absolute;',
'  left:0;',
'  top:0;',
'  width: 100%;',
'  height: 100%;',
'  background-color: whitesmoke;',
'  z-index:99;',
'  opacity:0.9;',    // <-- opacity you want for loader overlay
'  display: flex;',
'  justify-content: center;',
'  align-items: center;',
'  cursor: wait',
'}',
```

You'll get the effect you want.

**Comment by iansparks** [comment]
To be clear, it's just the addition of that one opacity line, I just show the surrounding lines for context.

**Comment by rayluo** [comment]
Thanks! That nails it. I ended up using `opacity:0.5` because the purpose is to let the real web page layout to be equally (if not more) visible with the overlay. I'll push the commit soon.
